
name: Mechanic 2

description: "The RoboFont Extension Manager"

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.robofontmechanic.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

# XXXX change this when a custom url is used
baseurl: "/" # the subpath of your site, e.g. /blog


permalink: /:title/

port: 8888

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  #- jekyll-gist
  - rouge
# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
